<?php

use Drupal\Core\Url;

/**
 * @file
 * Contains the media_formats_reports.module.
 */

/**
 * Implements hook_theme().
 */
function media_formats_reports_theme($existing, $type, $theme, $path) {
  return [
    'media_formats_reports_chart' => [
      'variables' => ['form' => null, 'show_csv_link' => null],
    ],
  ];
}

/**
 * Default preprocessor function for the media_formats_reports_theme hook.
 */
function template_preprocess_media_formats_reports_chart(&$variables) {
  $variables['attributes'] = [
    'id' => ['media_formats_reports_chart'],
  ];
  if ($variables['show_csv_link']) {
    $files_path = \Drupal::service('file_system')->realpath(file_default_scheme() . "://");
    $report_url = file_create_url(file_default_scheme() . "://media_types.csv");
    $variables['csv_url'] = $report_url;
  }
}

/**
 * Implements hook_page_attachments().
 */
function media_formats_reports_page_attachments(array &$attachments) {
  $current_path = \Drupal::service('path.current')->getPath();
  if ($current_path == '/admin/reports/media_formats') {
    $pie_chart_data = media_formats_reports_get_data();
    $attachments['#attached']['library'][] = 'media_formats_reports/media_formats_reports_chart';
    $attachments['#attached']['drupalSettings']['media_formats_reports']['chart_data'] = $pie_chart_data;
  }
}

/**
 * @return object
 *   A Chart.js dataset object.
 */
function media_formats_reports_get_data() {
  if ($tempstore = \Drupal::service('user.private_tempstore')->get('media_formats_reports')) {
    $report_type = $tempstore->get('media_formats_reports_report_type');
  }
  elseif (is_null($report_type)) {
    $report_type = 'mimetype';
  }
  else {
    $report_type = 'mimetype';
  }

  $data_source_service_id = 'media_formats_reports.datasource.' . $report_type;
  $data_source = \Drupal::service($data_source_service_id);
  $format_counts = $data_source->getData();

  // Populate the Chart.js dataset object.
  $num_formats = count($format_counts);
  $colors = media_formats_reports_get_chart_colors($num_formats);
  $dataset = new StdClass();
  $dataset->data = array_values($format_counts);
  $dataset->backgroundColor = media_formats_reports_get_chart_colors($num_formats);
  $pie_chart_data = array(
    'labels' => array_keys($format_counts),
    'datasets' =>  array($dataset),
  );

  // Write out a CSV for download.
  if ($tempstore->get('media_formats_reports_generate_csv')) {
    $files_path = \Drupal::service('file_system')->realpath(file_default_scheme() . "://");
    $csv_data = [
      array_keys($format_counts),
      array_values($format_counts),
    ];
    $fp = fopen($files_path . '/media_types.csv', 'w');
    foreach ($csv_data as $fields) {
      fputcsv($fp, $fields);
    }
    fclose($fp);
  }

  // We're finished with this session variable, so clear it for
  // the next rendering of the report page.
  $tempstore->delete('media_formats_reports_generate_csv');
  return $pie_chart_data;
}

/**
 * Generate a set of random colors to use in the pie chart.
 *
 * @param int $length
 *   The length of the array to generate.
 *
 * @return array
 *    An array of RGB values in the format required by Chart.js, e.g.,
 *    array('rgba(255, 99, 132)', 'rgba(54, 162, 235)', 'rgba(255, 206, 86)').
 */
function media_formats_reports_get_chart_colors($length) {
  $colors = [];
  for ($i = 1; $i <= $length; $i++) {
    $rgb_color = []; 
    foreach (['r', 'g', 'b'] as $color) {
      $rgb_color[$color] = rand(0, 255);
    }
    $colors[] = 'rgba(' . implode(',', $rgb_color) . ')';
  }
  return $colors;
}
