<?php

/**
 * @file
 * Contains the media_formats_reports.module.
 */

/**
 * Implements hook_theme().
 */
function media_formats_reports_theme($existing, $type, $theme, $path) {
  return [
    'media_formats_reports_chart' => [
      'variables' => [],
    ],
  ];
}

/**
 * Default preprocessor function for the media_formats_reports_theme hook.
 */
function template_preprocess_media_formats_reports_chart(&$variables) {
  $variables['attributes'] = [
    'id' => ['media_formats_reports_chart'],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function media_formats_reports_page_attachments(array &$attachments) {
  // $config = \Drupal::config('media_formats_reports.settings');
  $current_path = \Drupal::service('path.current')->getPath();

  if ($current_path == '/admin/reports/media_formats') {
    $pie_chart_data = media_formats_reports_get_data();
    $attachments['#attached']['library'][] = 'media_formats_reports/media_formats_reports_chart';
    $attachments['#attached']['drupalSettings']['media_formats_reports']['chart_data'] = $pie_chart_data;
  }
}

/**
 * @return object
 *   A Chart.js dataset object.
 */
function media_formats_reports_get_data() {
  $database = \Drupal::database();
  // This query gets Original Files (tid 17) and Preservation Masters (tid 18).
  $media_use_term_ids = '17,18';
  // Mimetype.
  $query = $database->query("SELECT field_mime_type_value AS t, count(field_mime_type_value) AS c FROM {media__field_mime_type}, {media__field_media_use} WHERE {media__field_mime_type}.bundle = {media__field_media_use}.bundle AND {media__field_media_use}.entity_id = {media__field_mime_type}.entity_id AND {media__field_media_use}.field_media_use_target_id IN (:tids) GROUP BY field_mime_type_value", [':tids' => $media_use_term_ids]);
  // DROID PUID.
  $query = $database->query("SELECT fits_droid_puid_value AS t, count(fits_droid_puid_value) AS c FROM media__fits_droid_puid GROUP BY fits_droid_puid_value");
  $result = $query->fetchAll();
  $labels = [];
  $values = [];
  foreach ($result as $format) {
    $labels[] = $format->t;
    $values[] = $format->c;
  }
  $num_formats = count($result);
  $colors = media_formats_reports_get_chart_colors($num_formats);
  $dataset = new StdClass();
  $dataset->data = $values;
  $dataset->backgroundColor = media_formats_reports_get_chart_colors($num_formats);
  $pie_chart_data = array(
    'labels' => $labels,
    'datasets' =>  array($dataset),
  );
  return $pie_chart_data;
}

/**
 * Generate a set of random colors to use in the pie chart.
 *
 * @param int $length
 *   The length of the array to generate.
 *
 * @return array
 *    An array of RGB values in the format required by Chart.js, e.g.,
 *    array('rgba(255, 99, 132)', 'rgba(54, 162, 235)', 'rgba(255, 206, 86)').
 */
function media_formats_reports_get_chart_colors($length) {
  $colors = [];
  for ($i = 1; $i <= $length; $i++) {
    $rgb_color = []; 
    foreach (['r', 'g', 'b'] as $color) {
      $rgb_color[$color] = rand(0, 255);
    }
    $colors[] = 'rgba(' . implode(',', $rgb_color) . ')';
  }
  return $colors;
}
